%definirea funcției și a figurii
function filtru(R,L,A,f,N,r,l,pha,C,form)
Fig=figure('Name','Filtru Trece Sus RL-Inductiv',...
 'Units','normalized',...
 'Position',[0.16 0.2 0.8 0.6],...
 'NumberTitle','off','color','#4DBEEE');


%Titlul proiectului
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.01 0.95 0.25 0.05],...
 'backgroundcolor','#4DBEEE',...
 'FontSize', 9,...
 'foregroundcolor','black',...
  'FontAngle', 'italic',...
 'String','FTS RL(Inductiv)-Schemă electrică:');



%inserearea scheme FTS_RL
[X2,map2]=imread('filtru.png');%--apelarea unei figuri ce conține schema electrică a unui fts RL
subplot('Position',[0 0.58 0.25 0.35]);%--poziționarea imaginii
imshow(X2,map2);%--folosirea unei funcții care o să afișeze imaginea
    

%grup pentru butoanele de reglare a parametrilor semnalului și al filtrului
   RadioGroup=uibuttongroup('Visible','on',...
                            'BackgroundColor',[0.3010 0.7450 0.9330],...
	                        'ForegroundColor','black',...
	                        'Title','Valorile componetelor filtrului și semnalului propus pentru generare:',...
	                        'FontSize',13,...
                            'TitlePosition','centertop',...
                            'Tag','radiobutton',...
                            'FontAngle', 'italic',...
                            'Position',[0.247 0.7 0.753 0.3]); 

 
  uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.5 0.1 0.3],...
 'FontSize',10,...
 'BackgroundColor',[0.3010 0.7450 0.9330],...
 'String','R(Ω)',...
 'Callback','close',...
 'FontAngle', 'italic',...
 'Parent',RadioGroup);

  Be=uicontrol('Style','edit',...              
               'Units','normalized',... 
                'FontSize',15,...
                'Position',[0.09 0.55 0.1 0.3],...              
                'foregroundcolor','r',...              
                'String',R,...              
                'Callback','R=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
                'Parent',RadioGroup);
 uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.5 0.1 0.3],...
 'FontSize',10,...
 'BackgroundColor',[0.3010 0.7450 0.9330],...
 'FontAngle', 'italic',...
 'String','L(H)',...
 'Callback','',...
 'Parent',RadioGroup);
  Be=uicontrol('Style','edit',...              
               'Units','normalized',... 
               'FontSize',15,...
               'Position',[0.3 0.55 0.1 0.3],...              
               'foregroundcolor','r',...              
               'String',L,...              
               'Callback','L=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
               'Parent',RadioGroup);
 
  %amplitudinea
  uicontrol('Style','text',...
            'Units','normalized',...
            'Position',[0.399 0.5 0.2 0.3],...
            'FontSize',10,...
            'FontAngle', 'italic',...
            'BackgroundColor',[0.3010 0.7450 0.9330],...
            'String','A(ampl)',...
            'Callback','close',...
            'Parent',RadioGroup);
  
  Be=uicontrol('Style','edit',...              
               'Units','normalized',... 
                'FontSize',15,...
                'Position',[0.55 0.55 0.1 0.3],...              
                'foregroundcolor','r',...              
                'String',A,...              
                'Callback','A=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
                'Parent',RadioGroup);


% frecvența
   uicontrol('Style','text',...
             'Units','normalized',...
             'Position',[0.65 0.5 0.2 0.3],...
              'FontSize',10,...
              'BackgroundColor',[0.3010 0.7450 0.9330],...
              'String','f(Hz)',...
              'FontAngle', 'italic',...
              'Callback','close',...
              'Parent',RadioGroup);
  
   
   Be=uicontrol('Style','edit',...              
                'Units','normalized',... 
                'FontSize',15,...
                'Position',[0.8 0.55 0.1 0.3],...              
                'foregroundcolor','r',...              
                'String',f,...              
                'Callback','f=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
                'Parent',RadioGroup);
  
   
   

   % faza inițială a semnalului
   uicontrol('Style','text',...
  'Units','normalized',...
  'Position',[0.65 0.2 0.2 0.3],...
  'FontSize',10,...
  'FontAngle', 'italic',...
  'BackgroundColor',[0.3010 0.7450 0.9330],...
  'String','ϕ(°)',...
  'Callback','',...
  'Parent',RadioGroup);
   
   
   
   Be=uicontrol('Style','edit',...              
                'Units','normalized',... 
                'FontSize',15,...
                'Position',[0.8 0.2 0.1 0.3],...              
                'foregroundcolor','r',...              
                'String',pha,...              
                'Callback','pha=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
                'Parent',RadioGroup);
  
   
   % numărul de perioade pe care va fi vizualizat semnalul
   uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.39 0.2 0.2 0.3],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'BackgroundColor',[0.3010 0.7450 0.9330],...
 'String','N(perioade)',...
 'Callback','',...
 'Parent',RadioGroup);
   
   
   
   Be=uicontrol('Style','edit',...              
                'Units','normalized',... 
                'FontSize',15,...
                'Position',[0.55 0.2 0.1 0.3],...              
                'foregroundcolor','r',...              
                'String',N,...              
                'Callback','N=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
                'Parent',RadioGroup);


   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%componenta continua a semnalului
   uicontrol('Style','text',...
             'Units','normalized',...
             'Position',[0.2 0.2 0.1 0.3],...
             'FontSize',10,...
             'FontAngle', 'italic',...
             'BackgroundColor',[0.3010 0.7450 0.9330],...
             'String','C(comp continuă)',...
             'Callback','',...
             'Parent',RadioGroup);
   
   
   Be=uicontrol('Style','edit',...              
                'Units','normalized',... 
                'FontSize',15,...
                'Position',[0.3 0.2 0.1 0.3],...              
                'foregroundcolor','r',...              
                'String',C,...              
                'Callback','C=str2num(get(gco,''string'')),close,filtru(R,L,A,f,N,r,l,pha,C,form);',...
                'Parent',RadioGroup);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% buton pentru graficul fazei-sl
  uicontrol('Style','pushbutton',... 
 'Units','normalized',...
 'Position',[0.55 0.47 0.2 .1],...
 'BackgroundColor','w',... 
 'FontAngle', 'italic',...
 'string','Diagramă ϕ(°) ',...
 'FontSize',10,...
 'Callback','close;grafic_fazab(f,R,L)');

  % buton pentru modulul funcției de transfer
  uicontrol('Style','pushbutton',... 
 'Units','normalized',...
 'Position',[0.55 0.58 0.2 .1],...
 'BackgroundColor','w',... 
 'FontAngle', 'italic',...
 'string','Diagramă H(jw) ',...
 'FontSize',10,...
 'Callback','close;grafic_modulul(R,L,f)');

  
  
  %afișarea unor mesaje de eroare în cazul introducerii unor valori nevalide
%pentru elementele care nu au fost standardizate 
     if f<=0 
    uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.1 0.13 0.22 0.34],...
        'BackgroundColor','r',...
        'foregroundcolor','black',...
        'String','Frecvența introdusă pentru semnal este nulă. Alegeți altă valoare',...
        'FontSize',10,...
        'FontName', 'Italic');
   end
    if f<=0 
    uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.41 0.08 0.55 0.34],... 
        'BackgroundColor','r',...
        'foregroundcolor','black',...
        'String','Frecvența introdusă pentru semnal este nulă. Alegeți altă valoare',...
        'FontSize',10,...
        'FontName', 'Italic');
    end
      if N<=0 
    uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.1 0.13 0.22 0.34],...
        'BackgroundColor','r',...
        'foregroundcolor','black',...
        'String','Numărul de perioade dat pentru reprezentarea semnalului este nul. Alegeți altă valoare',...
        'FontSize',10,...
         'FontAngle','italic');
   end
    if N<=0 
    uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.41 0.08 0.55 0.34],...
        'BackgroundColor','r',...
        'foregroundcolor','black',...
        'String','Numărul de perioade dat pentru reprezentarea semnalului este nul. Alegeți altă valoare',...
        'FontSize',10,...
         'FontAngle','italic');
end



%grup pentru butoanele popup de selectare a semnalului
RadioGroup2=uibuttongroup('Visible','on',...                                         
                         'Title','Tipul semnalului',... 
                         'ForegroundColor','white',...   
                         'FontAngle','italic',...
                         'foregroundcolor',[0.11, 0.44, 0.22],...
                         'BackgroundColor','#4DBEEE',...
                         'FontSize',11,...                          
                         'TitlePosition','centertop',...                          
                         'Tag','radiobutton',...                          
                         'Position',[0.31 0.55 0.18 0.1]);

            uicontrol('style','popup',...   
                      'units','normalized',...
                      'position',[0.1 0.7 0.8 0.10],...,
                      'foregroundcolor','black',...
                      'FontAngle','italic',...
                      'value',form,...
                      'string',' Sinusoidal|Triunghiular|Dreptunghiular|Fierastrău',... 
                      'Callback','form=get(gco,''value''),close;filtru(R,L,A,f,N,r,l,pha,C,form);',...
                      'Parent',RadioGroup2);
            
           %definirea și afișarea frecvenței de tăiere a filtrului
   ftai= R./(2*pi*L);
  uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.2 0.1 0.3],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'BackgroundColor',[0.3010 0.7450 0.9330],...
 'String','Ft(Hz)',...
 'Callback','',...
 'Parent',RadioGroup);
  
  
  uicontrol('Style','text',...          
               'Units','normalized',... 
                'FontSize',15,...
                'BackgroundColor','w',...
                'foregroundcolor','r',...            
                'Position',[0.09 0.2 0.1 0.3],...              
                'String',ftai,...              
                'Parent',RadioGroup);
%Definirea parametrilor necesari pentru generarea semnaleleor
T=1./f;
t=0:T/100:N*T;
w=2.*pi.*f;
def = pha*180/pi;      %fazza
numarator = 1i.*w.*L;            % număratorul funcției de transfer 
numitor = R + 1i.*w.*L;   % numitorul funcției de transfer 
modul = abs(numarator./numitor);        % modulul funcției de transfer 
phi = angle(numarator./numitor).*180./pi; % defazajul indus semnalului

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%definirea formei undelor de semnal de intrare/ieșire în funcție de tipul
%semnalului ales
if f<=ftai
if form==1     %Sinus
  
    Vi=C+A.*sin(2.*pi.*f.*t+def); 
    Vo = C + modul.*A.*sin(2.*pi.*f.*t + def + phi);
end
if form==2     %Triunghi

     Vi=C+A.*asin(sin(2.*pi.*f.*t+def));
     Vo = C + modul.*A.*asin(sin(2.*pi.*f.*t+def+phi));
end
%dreptunghic
if form==3    
 Vi= C+ A*square(2*pi*f*t+def);
   Vo = C + modul.*A*square(2*pi*f*t+def+phi);
 end
%sawtooth
 if form==4    
   
    Vi= C+ A*sawtooth(2*pi*f*t+def);
    Vo = C + modul.*A*sawtooth(2*pi*f*t+def+phi);
 end
end
if f>=ftai
    if form==1     %Sinus
  
    Vi=C+A.*sin(2.*pi.*f.*t+def); 
    Vo = C + modul.*A.*sin(2.*pi.*f.*t + def );
end
if form==2     %Triunghi

     Vi=C+A.*asin(sin(2.*pi.*f.*t+def));
     Vo = C + modul.*A.*asin(sin(2.*pi.*f.*t+def));
end
%dreptunghic
if form==3    
 Vi= C+ A*square(2*pi*f*t+def);
   Vo = C + modul.*A*square(2*pi*f*t+def);
 end
%sawtooth
 if form==4    
   
    Vi= C+ A*sawtooth(2*pi*f*t+def);
    Vo = C + modul.*A*sawtooth(2*pi*f*t+def);
 end
end
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


subplot('Position',[0.1 0.13 0.22 0.34])
plot(t,Vi,'g');
 hold on;
grid on;
title('Reprezentarea semnalului Vi generat de componentele alese',...
     'FontAngle','italic');

%atribuim un titlu graficului
xlabel('timp [s]',...
    'FontAngle','italic'); %scriem text pe axa x
ylabel('Amplitudine [V]',...
    'FontAngle','italic'); %scriem text pe axa y
hold on;

subplot('Position',[0.41 0.08 0.55 0.34])
plot(t,Vi,'r',t,Vo,'b');
legend('Vi','Vo',...
    'FontAngle','italic'); %inseram o legenda
hold on;
grid on;
        

title('Reprezentarea semnal Vi și Vo prelucrat de filtru',...
    'FontAngle','italic');%atribuim un titlu graficului
xlabel('timp [s]',...
    'FontAngle','italic'); %scriem text pe axa x
ylabel('Amplitudine [V]',...
    'FontAngle','italic'); %scriem text pe axa y
grid on;
hold on;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%crearea unui meniu cu label-uri direcționate spre documentație
fct=uimenu('Label','Documentație','Separator','on');   
 uimenu(fct,'Label','Titlul și Autorul proiectului','Callback','titlu');   
 uimenu(fct,'Label','Scopul proiectului','Callback','scop()'); 
 uimenu(fct,'Label','Ecuații și suport teoretic','Callback','teorie()');
uimenu(fct,'Label','Modul de utilizare al interfeței','Callback','prezent()');
uimenu(fct,'Label','Prezentare power point','Callback','powerpt()');
uimenu(fct,'Label','Listă pentru valorile standardizate','Callback','standard()');
uimenu(fct,'Label','Bibliografie','Callback','bibli()');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%standardizarea rezistorilor
htop=0;
conh=0;
switch r
case 1
  conh=1;
htop=[10 100 120 150 180 220 270 330 390 470 560 680 820 1000 1200 1500 1800 2200 2700 3300 3900 4700 5600 6800 8200 1000000 1200000 1500000 1800000 2200000 2700000 3300000 3900000 4700000 5600000 6800000 8200000]; 

    otherwise
        conh=0;
end
conh=1;
 
marg=length(htop);
gud=0;
for i=1:marg
    if htop(i)==R
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.41 0.08 0.55 0.34],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale rezitențelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.1 0.13 0.22 0.34],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic'); 
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%standardizrea bobinelor
 htop=0;
conh=0;
switch l
    case 1
        conh=1;
        htop=[0.0000018	0.000018	0.00018	0.0018 0.000002 0.00002	0.0002 0.002 0.0000022 0.000022	0.00022	0.0022 0.0000024 0.000024	0.00024	0.0024 0.0000027 0.000027	0.00027	0.0027 0.000003 0.00003	0.0003	0.003 0.0000033 0.000033 0.00033 0.0033 0.0000036 0.000036	0.00036	0.0036 0.0000039 0.000039	0.00039	0.0039 0.0000043 0.000043 0.00043 0.0043 0.0000047 0.000047	0.00047	0.0047 0.0000051 0.000051	0.00051	0.0051 0.0000056 0.000056 0.00056	0.0056 0.0000062 0.000062	0.00062	0.0062 0.0000068 0.000068 0.00068	0.0068 0.00000075 0.000075	0.00075	0.0075 0.0000082 0.000082	0.00082	0.0082 0.0000087 0.000087	0.00087	0.0087 0.0000091 0.000091	0.00091	0.0091];

otherwise
        conh=0;
end
conh=1;
 
marg2=length(htop);
gud=0;
for i=1:marg2
    if htop(i)==L
        gud=1;
        break
    end
end

if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.41 0.08 0.55 0.34],...
 'FontSize',10,...
 'FontAngle', 'italic',...
 'String','Valoarea aleasă nu se află printre valorile standardizate ale inductanțelor. Alegeți altă valoare'); 
end
if gud~=1
        uicontrol('Style','edit',...
 'Units','normalized',...
  'BackgroundColor','r',...
        'foregroundcolor','black',...
 'Position',[0.1 0.13 0.22 0.34],...
 'FontSize',10,...
 'String','EROARE',...
 'FontAngle', 'italic'); 
end


%buton de resetare a parametrilor filtrului și senalului la valorile
%predefinite
Bp1=uicontrol('Style','pushbutton',...       
              'Units','normalized',...             
              'Position',[0.78 0.54 0.2 0.1],... 
              'FontAngle','italic',...
              'backgroundcolor','w',...
              'FontSize',9,...
              'String','Resetare valori',...             
              'Callback','close,filtru(10,0.0091,7,500,5,1,1,0,0,1)');



end
 

