function grafic_fazab(f,R,L)

figure('Name','Reprezentare grafică-fază',...
             'Units','normalized',...
             'NumberTitle','off',...
             'Position',[0.1 0.1 0.8 0.8],...
             'Color','#4DBEEE');
         
 w=logspace(9,1,f);  % vectorul w = f apartinand [10^min, 10^max]
f0 = R./(2.*pi.*L); % frecventa de taiere
f1=w./(2.*pi);      % frecventa 
faza = 1*angle ((w.*1i.*L)./( R + w.*1i.*L )).*180./pi;             
defaza = pi/4.*180./pi;

subplot('Position', [0.1 0.33 0.85 0.50],...
     'FontAngle', 'italic');
semilogx(f1,faza,'r',f0,defaza,'*','LineWidth',3.5);  
hold on;
grid on;

title('Caracteristica de fază a RL trece sus',...
     'FontAngle', 'italic');
xlabel('frecvența [ Hz ]',...
 'FontAngle', 'italic');
ylabel('defazaj [ grade ]',...
 'FontAngle', 'italic');



  uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'BackgroundColor','w',... 
            'Position',[0.2 0.15 0.2 0.05],...
            'FontAngle', 'italic',...
            'String','Revenire la interfață',...
            'Fontsize',9,...
            'Callback','close;filtru_stat'); % buton de revenire la interfata

  uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'BackgroundColor','w',... 
            'Position',[0.6 0.15 0.2 0.05],...
            'FontAngle', 'italic',...
            'String','Ieșire din proiect',...
            'Fontsize',9,...
            'Callback','close'); % buton de iesire completa

end